import type { Metadata } from "next";
import { Source_Sans_3 as Font_sas } from "next/font/google";
import "./globals.css";

const Source_Sans_3 = Font_sas({
  variable: "--font-sas",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` font-sas ${Source_Sans_3.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
